/joy2twist:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 2
    axis_linear:
      x: 1
      y: 0
      z: -1
    require_enable_button: true
    enable_button: 5
    enable_turbo_button: 4
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 0.5
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 1.0
    scale_linear:
      x: 0.5
      y: 0.5
      z: 0.0
    scale_linear_turbo:
      x: 1.0
      y: 1.0
      z: 0.0
    use_sim_time: false
    frame: teleop_twist_joy
    inverted_reverse: false
    publish_stamped_twist: false

